version: "3.9"
services:
  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    networks:
      - web_network
  web:
    container_name: skills-trainer
    restart: always
    env_file: .env
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/skills-trainer
    ports:
      - "8000:8000"
    depends_on:
      - db
    networks:
      - web_network
  nginx:
    container_name: nginx
    restart: always
    image: "nginx:latest"
    ports:
      - "85:85"
    volumes:
      - ./nginx:/etc/nginx/conf.d
    networks:
      - web_network
    depends_on: 
      - appseed-app
networks:
  web_network:
    driver: bridge
 