# Generated by Django 4.0.8 on 2022-12-21 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0005_remove_answer_image_remove_question_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quiz',
            options={'verbose_name_plural': 'quizes'},
        ),
    ]
