# Generated by Django 4.0.8 on 2022-12-22 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0006_alter_quiz_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='time',
            field=models.IntegerField(default=30, help_text='duration in minutes'),
        ),
    ]
