# Generated by Django 4.0.8 on 2023-01-03 10:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0007_alter_question_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Technology',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
            ],
        ),
        migrations.RemoveField(
            model_name='question',
            name='prog_language',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='prog_language',
        ),
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('multiple choice', 'multiple choice'), ('open', 'open'), ('true/false', 'true/false')], max_length=64),
        ),
        migrations.AddField(
            model_name='question',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='quiz.category'),
        ),
        migrations.AddField(
            model_name='question',
            name='technology',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='quiz.technology'),
        ),
        migrations.AddField(
            model_name='quiz',
            name='category',
            field=models.ManyToManyField(to='quiz.category'),
        ),
        migrations.AddField(
            model_name='quiz',
            name='technology',
            field=models.ManyToManyField(to='quiz.technology'),
        ),
    ]
