# Generated by Django 4.0.8 on 2023-01-03 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0008_category_technology_remove_question_prog_language_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'categories'},
        ),
        migrations.AlterModelOptions(
            name='technology',
            options={'verbose_name_plural': 'technologies'},
        ),
        migrations.AlterField(
            model_name='quiz',
            name='category',
            field=models.ManyToManyField(to='quiz.category', verbose_name='category'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='technology',
            field=models.ManyToManyField(to='quiz.technology', verbose_name='technology'),
        ),
    ]
