# Generated by Django 4.0.8 on 2023-01-03 16:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0009_alter_category_options_alter_technology_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.category'),
        ),
        migrations.AlterField(
            model_name='question',
            name='technology',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.technology'),
        ),
    ]
