# Generated by Django 4.0.8 on 2023-01-12 10:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0010_alter_question_category_alter_question_technology'),
    ]

    operations = [
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('general_score', models.IntegerField(default=0)),
                ('junior_score', models.IntegerField(default=0)),
                ('number_of_junior_series', models.IntegerField(default=0)),
                ('regular_score', models.IntegerField(default=0)),
                ('number_of_regular_series', models.IntegerField(default=0)),
                ('senior_score', models.IntegerField(default=0)),
                ('number_of_senior_series', models.IntegerField(default=0)),
            ],
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='general_score',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='junior_score',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='number_of_junior_series',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='number_of_regular_series',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='number_of_senior_series',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='regular_score',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='senior_score',
        ),
        migrations.AddField(
            model_name='technology',
            name='score',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='quiz.score'),
        ),
    ]
