# Generated by Django 4.0.8 on 2023-01-12 11:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0012_remove_technology_score_score_quiz_score_technology'),
    ]

    operations = [
        migrations.AlterField(
            model_name='score',
            name='technology',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='quiz.technology'),
        ),
    ]
