# Generated by Django 4.0.8 on 2023-01-12 11:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0013_alter_score_technology'),
    ]

    operations = [
        migrations.AlterField(
            model_name='score',
            name='technology',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.PROTECT, to='quiz.technology'),
        ),
    ]
