# Generated by Django 4.0.8 on 2023-01-12 11:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0014_alter_score_technology'),
    ]

    operations = [
        migrations.AlterField(
            model_name='score',
            name='quiz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.quiz'),
        ),
        migrations.AlterField(
            model_name='score',
            name='technology',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='quiz.technology'),
        ),
    ]
