# Generated by Django 4.0.8 on 2023-01-16 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0016_seniority_remove_question_seniority_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='seniority',
            options={'verbose_name_plural': 'seniority'},
        ),
    ]
