# Generated by Django 4.0.8 on 2023-01-17 08:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0018_question_seniority_technology_seniority'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='technology',
            name='seniority',
        ),
        migrations.AddField(
            model_name='score',
            name='seniority',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='quiz.seniority'),
            preserve_default=False,
        ),
    ]
