# Generated by Django 4.0.8 on 2023-01-17 09:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0019_remove_technology_seniority_score_seniority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='score',
            name='seniority',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='quiz.seniority'),
        ),
    ]
