# Generated by Django 4.0.8 on 2023-01-19 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0021_question_uuid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='score',
            name='general_score',
        ),
        migrations.RemoveField(
            model_name='score',
            name='junior_score',
        ),
        migrations.RemoveField(
            model_name='score',
            name='number_of_junior_series',
        ),
        migrations.RemoveField(
            model_name='score',
            name='number_of_regular_series',
        ),
        migrations.RemoveField(
            model_name='score',
            name='number_of_senior_series',
        ),
        migrations.RemoveField(
            model_name='score',
            name='regular_score',
        ),
        migrations.RemoveField(
            model_name='score',
            name='senior_score',
        ),
        migrations.AddField(
            model_name='score',
            name='score_data',
            field=models.JSONField(null=True),
        ),
    ]
