# Generated by Django 4.0.8 on 2023-01-26 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0022_remove_score_general_score_remove_score_junior_score_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='mode',
            field=models.CharField(choices=[('recruitment', 'Recruitment'), ('training', 'Training')], default='training', max_length=32, verbose_name='Mode'),
            preserve_default=False,
        ),
    ]
