# Generated by Django 4.0.8 on 2023-02-09 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0023_quiz_mode'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quiz',
            options={'verbose_name_plural': 'quizzes'},
        ),
    ]
